import forms from '@tailwindcss/forms';
import containerQueries from '@tailwindcss/container-queries';

/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./admin/**/*.html",
    "./auth/**/*.html",
    "./buyer/**/*.html",
    "./mobile-buyer/**/*.html",
    "./mobile-seller/**/*.html",
    "./seller/**/*.html",
    "./components/**/*.js",
    "./src/**/*.js"
  ],
  theme: {
    extend: {
      colors: {
        "error": "#3D6B4F",
        "primary-container": "#8FAF82",
        "inverse-surface": "#343029",
        "secondary-fixed-dim": "#F7F3EC",
        "inverse-primary": "#a0d2b0",
        "on-surface": "#1f1b15",
        "on-tertiary-fixed-variant": "#54387e",
        "on-secondary-fixed-variant": "#324e29",
        "on-tertiary": "#ffffff",
        "primary": "#3D6B4F",
        "surface-tint": "#3a684c",
        "tertiary-fixed": "#ecdcff",
        "tertiary-container": "#7B5EA7",
        "on-primary-fixed-variant": "#214f36",
        "on-tertiary-container": "#e8d6ff",
        "inverse-on-surface": "#f8efe5",
        "on-secondary": "#ffffff",
        "surface-variant": "#e2e3df",
        "tertiary": "#7B5EA7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f3f4f0",
        "on-error": "#ffffff",
        "on-surface-variant": "#414942",
        "outline": "#717972",
        "tertiary-fixed-dim": "#d6baff",
        "on-error-container": "#3D6B4F",
        "secondary-container": "#8FAF82",
        "secondary-fixed": "#caecbb",
        "primary-fixed-dim": "#a0d2b0",
        "secondary": "#49663f",
        "on-secondary-fixed": "#062103",
        "background": "#FFFFFF",
        "surface-dim": "#d9dad6",
        "primary-fixed": "#bceecb",
        "outline-variant": "#F7F3EC",
        "on-primary": "#ffffff",
        "surface-container-high": "#e7e9e4",
        "surface-bright": "#FFFFFF",
        "on-primary-fixed": "#002110",
        "on-background": "#1a1c1a",
        "on-secondary-container": "#4d6a43",
        "surface-container": "#edeeea",
        "on-primary-container": "#b7e9c6",
        "surface": "#FFFFFF",
        "surface-container-highest": "#e2e3df",
        "error-container": "#F7F3EC",
        "on-tertiary-fixed": "#270550",
        
        // Brand/Custom Colors
        "parchment": "#F7F3EC",
        "sage": "#8FAF82",
        "forest": "#3D6B4F",
        "gold": "#C8973A",
        "violet": "#8B5CF6",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "full": "9999px"
      },
      spacing: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "24px",
        "xl": "40px",
        "margin-desktop": "64px",
        "unit": "8px",
        "margin-mobile": "20px",
        "container-max": "1280px",
        "container-max-width": "1280px",
        "gutter": "24px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        "body-sm": ["DM Sans", "sans-serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "title-md": ["DM Sans", "sans-serif"],
        "label-caps": ["DM Sans", "sans-serif"],
        "display-lg": ["Playfair Display", "serif"],
        "title-serif": ["Playfair Display", "serif"],
        "body-md": ["DM Sans", "sans-serif"],
        "data-price": ["Space Mono", "monospace"],
        "data-mono": ["Space Mono", "monospace"],
        "display-hero": ["Playfair Display", "serif"],
      },
      fontSize: {
        "headline-lg-mobile": ["28px", {"lineHeight": "36px", "fontWeight": "500"}],
        "body-lg": ["16px", {"lineHeight": "26px", "fontWeight": "400"}],
        "body-sm": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "headline-lg": ["32px", {"lineHeight": "40px", "fontWeight": "500"}],
        "headline-md": ["32px", {"lineHeight": "40px", "fontWeight": "400"}],
        "headline-sm": ["24px", {"lineHeight": "32px", "fontWeight": "600"}],
        "title-md": ["18px", {"lineHeight": "24px", "fontWeight": "600"}],
        "label-caps": ["12px", {"lineHeight": "16px", "letterSpacing": "0.1em", "fontWeight": "600"}],
        "display-lg": ["48px", {"lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "500"}],
        "display-hero": ["56px", {"lineHeight": "64px", "fontWeight": "700"}],
        "title-serif": ["20px", {"lineHeight": "28px", "fontWeight": "400"}],
        "body-md": ["14px", {"lineHeight": "20px", "fontWeight": "400"}],
        "data-price": ["18px", {"lineHeight": "24px", "fontWeight": "700"}]
      }
    }
  },
  plugins: [
    forms,
    containerQueries
  ]
}
